[package]
name = "rust_chat"
version = "0.2.0"
authors = ["chansuke <moonset20@gmail.com>"]

[dependencies]
mio = { git = "https://github.com/carllerche/mio" }
http-muncher = "0.2.0"
rustc-serialize = "0.3.15"
sha1 = "0.1.1"
byteorder = "0.5"

